version: "3"

services:
  jwt_utility:
    container_name: jwtutil
    build:
      context: .
      network: host
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - JWT_SECRET=a9ddbcaba8c0ac1a0a812dc0c2f08514b23f2db0a68343cb8199ebb38a6d91e4ebfb378e22ad39c2d01d0b4ec9c34aa91056862ddace3fbbd6852ee60c36acbf
